Using Local ActiveMQ Broker with Spring Boot --------------------------------------------
	@SpringBootApplication
	public class SfgJmsApplication {

		public static void main(String[] args) throws Exception {
	/* Comment out ActiveMQ server instantiation as we will be running it outside of the Spring Boot application now
			ActiveMQServer server = ActiveMQServers.newActiveMQServer(new ConfigurationImpl()
			.setPersistenceEnabled(false)
			.setJournalDirectory("target/data/journal") 			// Set local build directory
			.setSecurityEnabled(false));							// Disable security, so anybody can connect to it
	//		.addAcceptorConfiguration("invm", "vm://0"));	// Make the server accessible in the VM (from ActiveMQ server documentation). But this triggered an ugly error that 'Acceptor with id 0 already registered'

			server.start();											// Run ActiveMQ server within Spring Boot together with our client application (normally you would run this on a separate server, but is just for learning purposes)
	*/

			SpringApplication.run(SfgJmsApplication.class, args);
		}

	}

	POM.xml

	<!-- Comment out ActiveMQ server dependencies as we will be running it outside of the Spring Boot application now, otherwise Spring Boot will autoconfigure an ActiveMQ instance for us
		&lt;!&ndash; Add Support for embedded Apache Active MQ JMS server &ndash;&gt;
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>artemis-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>artemis-jms-server</artifactId>
		</dependency>-->

	MAY NEED TO DELETE LOCAL target FOLDER AS WELL

	RESULT

	2021-08-09 13:15:20.816 ERROR 138476 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

	org.springframework.jms.JmsSecurityException: AMQ229031: Unable to validate user from /172.17.0.1:55250. Username: null; SSL certificate subject DN: unavailable; nested exception is javax.jms.JMSSecurityException: AMQ229031: Unable to validate user from /172.17.0.1:55250. Username: null; SSL certificate subject DN: unavailable
		at org.springframework.jms.support.JmsUtils.convertJmsAccessException(JmsUtils.java:286) ~[spring-jms-5.3.6.jar:5.3.6]
		at org.springframework.jms.support.JmsAccessor.convertJmsAccessException(JmsAccessor.java:185) ~[spring-jms-5.3.6.jar:5.3.6]
		at org.springframework.jms.core.JmsTemplate.executeLocal(JmsTemplate.java:957) ~[spring-jms-5.3.6.jar:5.3.6]
		at org.springframework.jms.core.JmsTemplate.sendAndReceive(JmsTemplate.java:894) ~[spring-jms-5.3.6.jar:5.3.6]
		at guru.springframework.sfgjms.sender.HelloSender.sendAndReceiveMessage(HelloSender.java:46) ~[classes/:na]
		...
		Caused by: javax.jms.JMSSecurityException: AMQ229031: Unable to validate user from /172.17.0.1:55250. Username: null; SSL certificate subject DN: unavailable
		at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:540) ~[artemis-core-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:434) ~[artemis-core-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQClientProtocolManager.createSessionContext(ActiveMQClientProtocolManager.java:300) ~[artemis-core-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQClientProtocolManager.createSessionContext(ActiveMQClientProtocolManager.java:249) ~[artemis-core-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.createSessionChannel(ClientSessionFactoryImpl.java:1387) ~[artemis-core-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.createSessionInternal(ClientSessionFactoryImpl.java:691) ~[artemis-core-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.createSession(ClientSessionFactoryImpl.java:316) ~[artemis-core-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.jms.client.ActiveMQConnection.authorize(ActiveMQConnection.java:684) ~[artemis-jms-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:920) ~[artemis-jms-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:299) ~[artemis-jms-client-2.15.0.jar:2.15.0]
		at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:294) ~[artemis-jms-client-2.15.0.jar:2.15.0]
		at org.springframework.jms.connection.SingleConnectionFactory.doCreateConnection(SingleConnectionFactory.java:410) ~[spring-jms-5.3.6.jar:5.3.6]
		at org.springframework.jms.connection.SingleConnectionFactory.initConnection(SingleConnectionFactory.java:350) ~[spring-jms-5.3.6.jar:5.3.6]
		at org.springframework.jms.connection.SingleConnectionFactory.getConnection(SingleConnectionFactory.java:328) ~[spring-jms-5.3.6.jar:5.3.6]
		at org.springframework.jms.connection.SingleConnectionFactory.createConnection(SingleConnectionFactory.java:243) ~[spring-jms-5.3.6.jar:5.3.6]
		at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:196) ~[spring-jms-5.3.6.jar:5.3.6]
		at org.springframework.jms.core.JmsTemplate.executeLocal(JmsTemplate.java:946) ~[spring-jms-5.3.6.jar:5.3.6]
		... 15 common frames omitted
	Caused by: org.apache.activemq.artemis.api.core.ActiveMQSecurityException: AMQ229031: Unable to validate user from /172.17.0.1:55250. Username: null; SSL certificate subject DN: unavailable

	We are now trying to connect to our ActiveMQ server running on Docker but without user credentials => ActiveMQSecurityException

	SOLUTION:
		Add application.properties under 'resources' folder containing:

		spring.artemis.user=artemis
		spring.artemis.password=simetraehcapa